package person;

public enum CombinationFeature implements Feature {
    CREW_PARENT, EVIL_GENIOUS, MYSTERY_BEAUTY,
    SIMPLE_GUY, NERDY, STUPID_MINION,
    WORK_FAN, EFFECTIVE_MANAGER, SCHEMER,
    CHARMING_PERSON, WISE_ADVISOR, HYPERCOMPENSATION,
    LONER, AMEBA, MANIAC, PERFECTIONIST,
    VILLIAN, NUTTY_SCIENTIST,
    IDEAL_BEAUTY, MONSTER, JOKER, CANDID,
    ACTOR, STRONG, LEADER, FATAL_ONE, IRRESPONSIBLE,
    ANDROID, SLY, BEST_LOVER, SHY, SUPER_SMART, IRRATIONAL,
    TELEPAT, CONTRIVER, HERO, ROMANTIC, ARTIST, CHOOSEN_ONE
}
